# pyproject.toml
[build-system]
requires = [
    "setuptools",
    "wheel",
    "install-jdk",
    "jcc"
]
build-backend = "setuptools.build_meta"

[project]
name = "orekit"
version = "12.0"
dependencies = [
    "install-jdk",
]